/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MicrosoftPeriodAspNetCorePeriodMvcPeriodProblemDetails {
    #[serde(rename = "type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Option<String>>,
    #[serde(rename = "title", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub title: Option<Option<String>>,
    #[serde(rename = "status", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub status: Option<Option<i32>>,
    #[serde(rename = "detail", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub detail: Option<Option<String>>,
    #[serde(rename = "instance", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub instance: Option<Option<String>>,
}

impl MicrosoftPeriodAspNetCorePeriodMvcPeriodProblemDetails {
    pub fn new() -> MicrosoftPeriodAspNetCorePeriodMvcPeriodProblemDetails {
        MicrosoftPeriodAspNetCorePeriodMvcPeriodProblemDetails {
            r#type: None,
            title: None,
            status: None,
            detail: None,
            instance: None,
        }
    }
}


