/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// LinkSegmentOrientation : Specifies an orientation of a link segment.

/// Specifies an orientation of a link segment.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LinkSegmentOrientation {
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "north")]
    North,
    #[serde(rename = "south")]
    South,
    #[serde(rename = "east")]
    East,
    #[serde(rename = "west")]
    West,
    #[serde(rename = "northeast")]
    Northeast,
    #[serde(rename = "southeast")]
    Southeast,
    #[serde(rename = "northwest")]
    Northwest,
    #[serde(rename = "southwest")]
    Southwest,

}

impl ToString for LinkSegmentOrientation {
    fn to_string(&self) -> String {
        match self {
            Self::Unknown => String::from("unknown"),
            Self::North => String::from("north"),
            Self::South => String::from("south"),
            Self::East => String::from("east"),
            Self::West => String::from("west"),
            Self::Northeast => String::from("northeast"),
            Self::Southeast => String::from("southeast"),
            Self::Northwest => String::from("northwest"),
            Self::Southwest => String::from("southwest"),
        }
    }
}

impl Default for LinkSegmentOrientation {
    fn default() -> LinkSegmentOrientation {
        Self::Unknown
    }
}




