/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// JourneysPeriodLinkSegmentApiModel : Represents a segment of a departure access link, arrival access link or destination link.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct JourneysPeriodLinkSegmentApiModel {
    /// Segment name.
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "maneuver", skip_serializing_if = "Option::is_none")]
    pub maneuver: Option<crate::models::LinkSegmentManeuver>,
    #[serde(rename = "orientation", skip_serializing_if = "Option::is_none")]
    pub orientation: Option<crate::models::LinkSegmentOrientation>,
    /// Description for the maneuver.
    #[serde(rename = "maneuverDescription", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub maneuver_description: Option<Option<String>>,
    /// Distance for this segment in meter.
    #[serde(rename = "distanceInMeters", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub distance_in_meters: Option<Option<i32>>,
}

impl JourneysPeriodLinkSegmentApiModel {
    /// Represents a segment of a departure access link, arrival access link or destination link.
    pub fn new() -> JourneysPeriodLinkSegmentApiModel {
        JourneysPeriodLinkSegmentApiModel {
            name: None,
            maneuver: None,
            orientation: None,
            maneuver_description: None,
            distance_in_meters: None,
        }
    }
}


