/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// JourneyDetailsPeriodChannelApiModel : Information about a channel related to the ticket suggestion.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct JourneyDetailsPeriodChannelApiModel {
    /// The channel id.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// The channel-specific ticket name, set if the channel is configured to override the default  product name.
    #[serde(rename = "ticketName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ticket_name: Option<Option<String>>,
}

impl JourneyDetailsPeriodChannelApiModel {
    /// Information about a channel related to the ticket suggestion.
    pub fn new() -> JourneyDetailsPeriodChannelApiModel {
        JourneyDetailsPeriodChannelApiModel {
            id: None,
            ticket_name: None,
        }
    }
}


