/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ArrivalDetailsIncludeType : The different kinds of detailed information that could be included in a get arrival details request.

/// The different kinds of detailed information that could be included in a get arrival details request.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ArrivalDetailsIncludeType {
    #[serde(rename = "servicejourneycalls")]
    Servicejourneycalls,
    #[serde(rename = "servicejourneycoordinates")]
    Servicejourneycoordinates,

}

impl ToString for ArrivalDetailsIncludeType {
    fn to_string(&self) -> String {
        match self {
            Self::Servicejourneycalls => String::from("servicejourneycalls"),
            Self::Servicejourneycoordinates => String::from("servicejourneycoordinates"),
        }
    }
}

impl Default for ArrivalDetailsIncludeType {
    fn default() -> ArrivalDetailsIncludeType {
        Self::Servicejourneycalls
    }
}




