/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TimeLimitation {
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "heltid")]
    Heltid,
    #[serde(rename = "lagtrafik")]
    Lagtrafik,
    #[serde(rename = "skolkort04till19")]
    Skolkort04till19,
    #[serde(rename = "skolkort04till22")]
    Skolkort04till22,
    #[serde(rename = "skolkort04till1930")]
    Skolkort04till1930,
    #[serde(rename = "fritid100")]
    Fritid100,
    #[serde(rename = "fritidkomplement")]
    Fritidkomplement,
    #[serde(rename = "fritidvardag19till22")]
    Fritidvardag19till22,
    #[serde(rename = "fritidvardag14till24")]
    Fritidvardag14till24,
    #[serde(rename = "fritidkvallhelg")]
    Fritidkvallhelg,
    #[serde(rename = "fritidkvallhelglov")]
    Fritidkvallhelglov,
    #[serde(rename = "fritidjulsommarlov")]
    Fritidjulsommarlov,
    #[serde(rename = "fritidale")]
    Fritidale,

}

impl ToString for TimeLimitation {
    fn to_string(&self) -> String {
        match self {
            Self::Unknown => String::from("unknown"),
            Self::Heltid => String::from("heltid"),
            Self::Lagtrafik => String::from("lagtrafik"),
            Self::Skolkort04till19 => String::from("skolkort04till19"),
            Self::Skolkort04till22 => String::from("skolkort04till22"),
            Self::Skolkort04till1930 => String::from("skolkort04till1930"),
            Self::Fritid100 => String::from("fritid100"),
            Self::Fritidkomplement => String::from("fritidkomplement"),
            Self::Fritidvardag19till22 => String::from("fritidvardag19till22"),
            Self::Fritidvardag14till24 => String::from("fritidvardag14till24"),
            Self::Fritidkvallhelg => String::from("fritidkvallhelg"),
            Self::Fritidkvallhelglov => String::from("fritidkvallhelglov"),
            Self::Fritidjulsommarlov => String::from("fritidjulsommarlov"),
            Self::Fritidale => String::from("fritidale"),
        }
    }
}

impl Default for TimeLimitation {
    fn default() -> TimeLimitation {
        Self::Unknown
    }
}




