/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// LocationByCoordinatesType : A subset of LocationType

/// A subset of LocationType
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LocationByCoordinatesType {
    #[serde(rename = "stoparea")]
    Stoparea,
    #[serde(rename = "stoppoint")]
    Stoppoint,
    #[serde(rename = "pointofinterest")]
    Pointofinterest,
    #[serde(rename = "metastation")]
    Metastation,

}

impl ToString for LocationByCoordinatesType {
    fn to_string(&self) -> String {
        match self {
            Self::Stoparea => String::from("stoparea"),
            Self::Stoppoint => String::from("stoppoint"),
            Self::Pointofinterest => String::from("pointofinterest"),
            Self::Metastation => String::from("metastation"),
        }
    }
}

impl Default for LocationByCoordinatesType {
    fn default() -> LocationByCoordinatesType {
        Self::Stoparea
    }
}




