/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PaginationLinks : Pagination navigation links.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PaginationLinks {
    /// Link to the previous results page, if available, otherwise null.
    #[serde(rename = "previous", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub previous: Option<Option<String>>,
    /// Link to the next results page, if available, otherwise null. Not guaranteed to give a result if called.
    #[serde(rename = "next", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub next: Option<Option<String>>,
    /// Link to the current results page, if available, otherwise null. Not guaranteed to give a result if called.
    #[serde(rename = "current", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub current: Option<Option<String>>,
}

impl PaginationLinks {
    /// Pagination navigation links.
    pub fn new() -> PaginationLinks {
        PaginationLinks {
            previous: None,
            next: None,
            current: None,
        }
    }
}


