/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TravellerCategory {
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "adult")]
    Adult,
    #[serde(rename = "youth")]
    Youth,

}

impl ToString for TravellerCategory {
    fn to_string(&self) -> String {
        match self {
            Self::Unknown => String::from("unknown"),
            Self::Adult => String::from("adult"),
            Self::Youth => String::from("youth"),
        }
    }
}

impl Default for TravellerCategory {
    fn default() -> TravellerCategory {
        Self::Unknown
    }
}




