/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// JourneyDetailsPeriodServiceJourneyApiModel : Information about a service journey.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct JourneyDetailsPeriodServiceJourneyApiModel {
    /// 16-digit Västtrafik service journey gid that the trip leg is a part of.
    #[serde(rename = "gid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub gid: Option<Option<String>>,
    /// A description of the direction.
    #[serde(rename = "direction", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub direction: Option<Option<String>>,
    #[serde(rename = "line", skip_serializing_if = "Option::is_none")]
    pub line: Option<Box<crate::models::JourneyDetailsPeriodLineDetailsApiModel>>,
    /// The coordinates on the service journey.
    #[serde(rename = "serviceJourneyCoordinates", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub service_journey_coordinates: Option<Option<Vec<crate::models::CoordinateApiModel>>>,
    /// All calls on the service journey.
    #[serde(rename = "callsOnServiceJourney", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub calls_on_service_journey: Option<Option<Vec<crate::models::JourneyDetailsPeriodCallDetailsApiModel>>>,
}

impl JourneyDetailsPeriodServiceJourneyApiModel {
    /// Information about a service journey.
    pub fn new() -> JourneyDetailsPeriodServiceJourneyApiModel {
        JourneyDetailsPeriodServiceJourneyApiModel {
            gid: None,
            direction: None,
            line: None,
            service_journey_coordinates: None,
            calls_on_service_journey: None,
        }
    }
}


