/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DeparturesAndArrivalsPeriodArrivalDetailsApiModel {
    #[serde(rename = "serviceJourneys", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub service_journeys: Option<Option<Vec<crate::models::DeparturesAndArrivalsPeriodServiceJourneyDetailsApiModel>>>,
}

impl DeparturesAndArrivalsPeriodArrivalDetailsApiModel {
    pub fn new() -> DeparturesAndArrivalsPeriodArrivalDetailsApiModel {
        DeparturesAndArrivalsPeriodArrivalDetailsApiModel {
            service_journeys: None,
        }
    }
}


