/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// JourneyTransportSubMode : A subset of TransportMode

/// A subset of TransportMode
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum JourneyTransportSubMode {
    #[serde(rename = "vasttagen")]
    Vasttagen,
    #[serde(rename = "longdistancetrain")]
    Longdistancetrain,
    #[serde(rename = "regionaltrain")]
    Regionaltrain,

}

impl ToString for JourneyTransportSubMode {
    fn to_string(&self) -> String {
        match self {
            Self::Vasttagen => String::from("vasttagen"),
            Self::Longdistancetrain => String::from("longdistancetrain"),
            Self::Regionaltrain => String::from("regionaltrain"),
        }
    }
}

impl Default for JourneyTransportSubMode {
    fn default() -> JourneyTransportSubMode {
        Self::Vasttagen
    }
}




