/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// JourneyDetailsPeriodZoneApiModel : Information about a zone related to the ticket suggestion.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct JourneyDetailsPeriodZoneApiModel {
    /// The zone id.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
}

impl JourneyDetailsPeriodZoneApiModel {
    /// Information about a zone related to the ticket suggestion.
    pub fn new() -> JourneyDetailsPeriodZoneApiModel {
        JourneyDetailsPeriodZoneApiModel {
            id: None,
        }
    }
}


