/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct JourneyDetailsPeriodTariffZoneApiModel {
    /// The 16-digit Västtrafik gid of the tariff zone.
    #[serde(rename = "gid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub gid: Option<Option<String>>,
    /// The name of the tariff zone.
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    /// The tariff zone number.
    #[serde(rename = "number", skip_serializing_if = "Option::is_none")]
    pub number: Option<i32>,
    /// The short name of the tariff zone.
    #[serde(rename = "shortName", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub short_name: Option<Option<String>>,
}

impl JourneyDetailsPeriodTariffZoneApiModel {
    pub fn new() -> JourneyDetailsPeriodTariffZoneApiModel {
        JourneyDetailsPeriodTariffZoneApiModel {
            gid: None,
            name: None,
            number: None,
            short_name: None,
        }
    }
}


