/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CoordinateApiModel : Information about the coordinates



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CoordinateApiModel {
    /// The latitude of this position (WGS84).
    #[serde(rename = "latitude", skip_serializing_if = "Option::is_none")]
    pub latitude: Option<f64>,
    /// The longitude of this position (WGS84).
    #[serde(rename = "longitude", skip_serializing_if = "Option::is_none")]
    pub longitude: Option<f64>,
    /// The elevation of this position (WGS84).
    #[serde(rename = "elevation", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub elevation: Option<Option<f64>>,
    /// The coordinate is on the tripleg.
    #[serde(rename = "isOnTripLeg", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_on_trip_leg: Option<Option<bool>>,
    /// The coordinate is on the first call of the leg.
    #[serde(rename = "isTripLegStart", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_trip_leg_start: Option<Option<bool>>,
    /// The coordinate is on the last call of the leg.
    #[serde(rename = "isTripLegStop", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_trip_leg_stop: Option<Option<bool>>,
}

impl CoordinateApiModel {
    /// Information about the coordinates
    pub fn new() -> CoordinateApiModel {
        CoordinateApiModel {
            latitude: None,
            longitude: None,
            elevation: None,
            is_on_trip_leg: None,
            is_trip_leg_start: None,
            is_trip_leg_stop: None,
        }
    }
}


