/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PositionTransportMode {
    #[serde(rename = "tram")]
    Tram,
    #[serde(rename = "bus")]
    Bus,
    #[serde(rename = "ferry")]
    Ferry,
    #[serde(rename = "train")]
    Train,
    #[serde(rename = "taxi")]
    Taxi,

}

impl ToString for PositionTransportMode {
    fn to_string(&self) -> String {
        match self {
            Self::Tram => String::from("tram"),
            Self::Bus => String::from("bus"),
            Self::Ferry => String::from("ferry"),
            Self::Train => String::from("train"),
            Self::Taxi => String::from("taxi"),
        }
    }
}

impl Default for PositionTransportMode {
    fn default() -> PositionTransportMode {
        Self::Tram
    }
}




