/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ProductInstanceTypeApiModel : Specifies whether or not the product is dynamically based on the journey route.

/// Specifies whether or not the product is dynamically based on the journey route.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ProductInstanceTypeApiModel {
    #[serde(rename = "static")]
    Static,
    #[serde(rename = "dynamic")]
    Dynamic,

}

impl ToString for ProductInstanceTypeApiModel {
    fn to_string(&self) -> String {
        match self {
            Self::Static => String::from("static"),
            Self::Dynamic => String::from("dynamic"),
        }
    }
}

impl Default for ProductInstanceTypeApiModel {
    fn default() -> ProductInstanceTypeApiModel {
        Self::Static
    }
}




