/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TimeValidityType {
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "amountunit")]
    Amountunit,
    #[serde(rename = "fromtodate")]
    Fromtodate,
    #[serde(rename = "fromtodatetime")]
    Fromtodatetime,

}

impl ToString for TimeValidityType {
    fn to_string(&self) -> String {
        match self {
            Self::Unknown => String::from("unknown"),
            Self::Amountunit => String::from("amountunit"),
            Self::Fromtodate => String::from("fromtodate"),
            Self::Fromtodatetime => String::from("fromtodatetime"),
        }
    }
}

impl Default for TimeValidityType {
    fn default() -> TimeValidityType {
        Self::Unknown
    }
}




