/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// JourneyDetailsPeriodPunchConfigurationDurationApiModel : Describes the duration of validity of a single punch.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct JourneyDetailsPeriodPunchConfigurationDurationApiModel {
    #[serde(rename = "unit", skip_serializing_if = "Option::is_none")]
    pub unit: Option<crate::models::PunchConfigurationDurationUnitApiModel>,
    /// Duration of validity of a single punch.
    #[serde(rename = "amount", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub amount: Option<Option<i32>>,
}

impl JourneyDetailsPeriodPunchConfigurationDurationApiModel {
    /// Describes the duration of validity of a single punch.
    pub fn new() -> JourneyDetailsPeriodPunchConfigurationDurationApiModel {
        JourneyDetailsPeriodPunchConfigurationDurationApiModel {
            unit: None,
            amount: None,
        }
    }
}


