/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// DeparturesAndArrivalsPeriodCoordinateApiModel : Information about the coordinates



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DeparturesAndArrivalsPeriodCoordinateApiModel {
    /// The latitude of this position (WGS84).
    #[serde(rename = "latitude", skip_serializing_if = "Option::is_none")]
    pub latitude: Option<f64>,
    /// The longitude of this position (WGS84).
    #[serde(rename = "longitude", skip_serializing_if = "Option::is_none")]
    pub longitude: Option<f64>,
    /// The elevation of this position (WGS84).
    #[serde(rename = "elevation", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub elevation: Option<Option<f64>>,
}

impl DeparturesAndArrivalsPeriodCoordinateApiModel {
    /// Information about the coordinates
    pub fn new() -> DeparturesAndArrivalsPeriodCoordinateApiModel {
        DeparturesAndArrivalsPeriodCoordinateApiModel {
            latitude: None,
            longitude: None,
            elevation: None,
        }
    }
}


