/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TransportSubMode {
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "none")]
    None,
    #[serde(rename = "vasttagen")]
    Vasttagen,
    #[serde(rename = "longdistancetrain")]
    Longdistancetrain,
    #[serde(rename = "regionaltrain")]
    Regionaltrain,

}

impl ToString for TransportSubMode {
    fn to_string(&self) -> String {
        match self {
            Self::Unknown => String::from("unknown"),
            Self::None => String::from("none"),
            Self::Vasttagen => String::from("vasttagen"),
            Self::Longdistancetrain => String::from("longdistancetrain"),
            Self::Regionaltrain => String::from("regionaltrain"),
        }
    }
}

impl Default for TransportSubMode {
    fn default() -> TransportSubMode {
        Self::Unknown
    }
}




