/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 * Generated by: https://openapi-generator.tech
 */

/// JourneyDetailsPeriodPunchConfigurationApiModel : Represents punch configuration.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct JourneyDetailsPeriodPunchConfigurationApiModel {
    /// Punch quota of a single ticket.
    #[serde(rename = "quota", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub quota: Option<Option<i32>>,
    #[serde(rename = "duration", skip_serializing_if = "Option::is_none")]
    pub duration: Option<Box<crate::models::JourneyDetailsPeriodPunchConfigurationDurationApiModel>>,
}

impl JourneyDetailsPeriodPunchConfigurationApiModel {
    /// Represents punch configuration.
    pub fn new() -> JourneyDetailsPeriodPunchConfigurationApiModel {
        JourneyDetailsPeriodPunchConfigurationApiModel {
            quota: None,
            duration: None,
        }
    }
}


