/*
 * Planera Resa
 *
 * Sök och planera resor med Västtrafik
 *
 * The version of the OpenAPI document: v4
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DeparturesAndArrivalsPeriodDepartureDetailsApiModel {
    #[serde(rename = "serviceJourneys", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub service_journeys: Option<Option<Vec<crate::models::DeparturesAndArrivalsPeriodServiceJourneyDetailsApiModel>>>,
    #[serde(rename = "occupancy", skip_serializing_if = "Option::is_none")]
    pub occupancy: Option<Box<crate::models::OccupancyInformationApiModel>>,
}

impl DeparturesAndArrivalsPeriodDepartureDetailsApiModel {
    pub fn new() -> DeparturesAndArrivalsPeriodDepartureDetailsApiModel {
        DeparturesAndArrivalsPeriodDepartureDetailsApiModel {
            service_journeys: None,
            occupancy: None,
        }
    }
}


